name: Сборка ЖД Комплекса APK v15.0

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v4

    - name: Установка Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Установка Bubblewrap CLI
      run: npm install -g @bubblewrap/cli

    - name: Установка Java (JDK)
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Сборка Android проекта и инъекция прав
      run: |
        bubblewrap init --manifest=manifest.json --meta=twa-manifest.json --directory=./build-twa --meta-output=twa-manifest.json || true
        echo '{"features": {"backgroundLocation": true}, "alphaDependencies": true}' >> twa-manifest.json
        bubblewrap build --manifest=twa-manifest.json
        
    - name: Выгрузка готового APK в артефакты
      uses: actions/upload-artifact@v4
      with:
        name: Railway_BCH_v15_App
        path: ./*.apk
